
GET http://localhost:5094/members


###
GET http://localhost:5094/members/5

###
POST http://localhost:5094/members
Content-Type: application/json

{
  "firstName": "Manny",
  "lastName" : "Navarro",
  "email": "mannynav7794@gmail.com",
  "phoneNumber": "8566765417",
  "height": 180,
  "weight": 100,
  "goal": "Add weight",
  "joiningDate": "2021-09-01"
}


###
PUT http://localhost:5094/members/3
Content-Type: application/json

{
  "firstName": "Chloe",
  "lastName": "Doe",
  "email": "Chloedoe@gmail.com",
  "phoneNumber": "111111111",
  "height": 180,
  "weight": 40,
  "goal": "Lose Weight",
  "joiningDate": "2021-10-10"
}


###
DELETE http://localhost:5094/members/3